### ISSUE TITLE
Fix code scanning alert - Inefficient regular expression

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-nodejs#195]
Tracking issue for:
- [ ] https://github.com/openfoodfacts/openfoodfacts-nodejs/security/code-scanning/3

**Comment by danizavtz** [comment]
I tried read this bug, but I think I do not have enough permission to check this issue. It gives me a 404 not found error. (I'm logged in github).

**Comment by VaiTon** [comment]
It is fixed now
