### ISSUE TITLE
Add support for nutrient prediction

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-nodejs#541]
### Problem
- Nutrient extraction was just deployed on Robotoff :tada:
https://robotoff.openfoodfacts.org/api/v1/insights?barcode=3270160824182&insight_types=nutrient_extraction
The model is run for every new image that comes in, and we create a Robotoff insight if the model extracted nutrients that were not already present.

**Comment by gciluffo** [comment]
@teolemon I can take a stab at this one.

**Comment by teolemon** [comment]
Yes, of course @gciluffo , assigning you 👍

**Comment by teolemon** [comment]
@raphael0202 @alexfauquette FYI
