### ISSUE TITLE
Create a NPM package

### ISSUE THREAD

**Issue by astagi** [openfoodfacts/openfoodfacts-nodejs#64]
Having this module on NPM would be great 📦🙂

**Comment by locness3** [comment]
I don't understand why it's not.

**Comment by teolemon** [comment]
@locness3 @astagi I've created a npm org, added the CI token as a repository secret, and added a start for GitHub Actions:
https://github.com/openfoodfacts/openfoodfacts-nodejs/pull/134

Would you be interested in creating it ? Also, I've invited @astagi to the OFF org on npm
https://docs.github.com/en/actions/guides/publishing-nodejs-packages

**Comment by astagi** [comment]
@teolemon I've received the invitation, thanks! I'll create the package asap 📦

**Comment by astagi** [comment]
@teolemon sorry I missed the PR you referenced with the github action for auto publishing, it looks great! I suggest to run tests before publishing as I commented.

I've just opened a new PR to fix tests in CI, please check it out #135

**Comment by teolemon** [comment]
@astagi your PR was merged. We can proceed to packaging 👍

**Comment by jbeynar** [comment]
Done: https://www.npmjs.com/package/openfoodfacts-nodejs
